-- Q8 --
SELECT 
E.EMPNO AS EMPLOYEE_NUMBER,
E.ENAME AS EMPLOYEE_NAME,
IFNULL (M.EMPNO, '-') AS MANAGER_EMPNO,
IFNULL(M.ENAME, 'NO MANAGER') AS MANAGER_NAME
FROM 
EMPLOYEE E
  LEFT JOIN EMPLOYEE  M ON E.MGR = M.EMPNO;
  
  -- Q9 --
  SELECT
  D.DEPTNO AS DEPARTMENT_NUMBER,
  D.DNAME AS DEPARTMENT_NAME,
  SUM(E.SAL) as TOTAL_SALARY
  FROM
  EMPLOYEE E
     INNER JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
     GROUP BY D.DNAME, D.DEPTNO;
     

     -- ADD LOCATION COLUMN --
     ALTER TABLE DEPARTMENT
     ADD COLUMN LOCATION VARCHAR(255);
     SELECT * FROM DEPARTMENT;
-- ADDING LOCATION VALUE ---
UPDATE DEPARTMENT
SET LOCATION = 'SWEDEN' WHERE DEPTNO = 30;

-- Q10 --
     SELECT 
     E.EMPNO AS EMPLOYEE_NUMBER,
     E.ENAME AS EMPLOYEE_NAME,
     D.LOCATION AS POSTING_PLACE
     FROM
     EMPLOYEE E
     INNER JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO;
     
-- Q11 --
     SELECT 
     E.ENAME AS EMPLOYEE_NAME,
     D.DNAME AS DEPARTMENT_NAME
     FROM
     EMPLOYEE E INNER JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO;
     
  