USE EMPLOYEE;
-- Q1 --
SELECT 
E.ENAME, E.JOB 
FROM 
EMPLOYEE E INNER JOIN EMPLOYEE M
ON E.MGR = M.EMPNO
WHERE E.SAL < M.SAL
AND E.SAL > ANY(
                 SELECT SAL FROM EMPLOYEE WHERE JOB = 'MANAGER'
                 );

-- Q2 --
SELECT COUNT(*) AS TOTAL_EMPLOYEE
FROM
EMPLOYEE E INNER JOIN EMPLOYEE M
ON E.MGR = M.EMPNO
WHERE E.SAL > M.SAL;

-- Q3 --
SELECT E.ENAME FROM EMPLOYEE E JOIN EMPLOYEE M
ON E.MGR = M.EMPNO
WHERE E.JOB = 'MANAGER' AND M.JOB <> 'PRESIDENT';

-- Q4 --
SET SQL_SAFE_UPDATES = 0;
DELETE FROM DEPARTMENT
WHERE DEPTNO NOT IN (
                                          SELECT DISTINCT DEPTNO FROM EMPLOYEE
                                          );
                                          
-- Q5 --
DELETE FROM EMPLOYEE
WHERE DEPTNO NOT IN(
							SELECT DEPTNO FROM DEPARTMENT
                            );
                            
-- Q6 --
SELECT ENAME, SAL
FROM EMPLOYEE WHERE SAL NOT BETWEEN
(SELECT MIN(MINPAY) FROM SALGRADE) AND
(SELECT MAX(MAXPAY) FROM SALGRADE);

-- Q7 --
SELECT ENAME, SAL, COMM,
(SAL + IFNULL(COMM,0)) AS NET_PAY
FROM EMPLOYEE
WHERE 
(SAL + IFNULL(COMM,0)) >= ANY (
                     SELECT SAL FROM EMPLOYEE
                     );
-- Q8 --
SELECT ENAME FROM EMPLOYEE E
INNER JOIN DEPARTMENT D
ON E.DEPTNO = D.DEPTNO
WHERE D.DNAME IN('SALES','RESEARCH');

-- Q9 --
SELECT E.ENAME, S.GRADE
FROM
EMPLOYEE E JOIN SALGRADE S ON E.SAL
BETWEEN MINPAY AND MAXPAY
WHERE E.ENAME = 'JONES';

-- Q10 --
SELECT D.DNAME FROM DEPARTMENT D
WHERE LENGTH(D.DNAME) IN(
                       SELECT COUNT(*) FROM EMPLOYEE GROUP BY DEPTNO
                       );
