use employee;

insert into
salgrade values
-- FORMAT --> (grade,minpay,maxpay) --
(1, 700, 1200),
(2, 1201, 1400),
(3, 1401, 2000),
(4, 2001, 3000),
(5, 3001, 9999);

-- display employees with their dept name Q1--
select E.empno,E.job, E.sal,
E.deptno, D.dname
from
-- joining --
employee E inner join department D 
ON E.deptno = D.deptno;

-- display  employee whose manager is Jones Q2 --
SELECT
E.ENAME AS EMPLOYEE_NAME,
MG.ENAME AS MANAGER_NAME
from
EMPLOYEE E JOIN EMPLOYEE MG
on E.MGR  = MG.EMPNO
where MG.ENAME = 'jones';

-- Q3 -

SELECT 
E.ENAME AS EMPLOYEE_NAME, E.JOB AS EMPLOYEE_JOB,
D.DNAME AS DEPARTMENT_NAME,
MG.ENAME AS MANAGER_NAME,
SG.GRADE AS GRADEPAY
FROM 
EMPLOYEE E
INNER JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
JOIN EMPLOYEE MG ON E.MGR = MG.EMPNO
JOIN SALGRADE SG ON E.SAL BETWEEN MINPAY AND MAXPAY
ORDER BY D.DNAME;

-- Q4 --
SELECT
E.EMPNO AS EMPLOYEE_NUMBER, E.ENAME AS EMPLOYEE_NAME, E.SAL AS SALARY,
D.DNAME AS DEPARTMENT_NAME,
SG.GRADE AS GRADE_PAY
FROM
EMPLOYEE E
INNER JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
INNER JOIN SALGRADE SG ON E.SAL BETWEEN MINPAY AND MAXPAY
WHERE JOB <> 'CLERK'
ORDER BY E.SAL DESC;

-- Q5 --
SELECT
E.ENAME AS EMPLOYEE_NAME, E.JOB AS EMPLOYEE_JOB,
IFNULL(MG.ENAME, 'NO MANAGER') AS MANAGER_NAME
FROM
EMPLOYEE E LEFT JOIN EMPLOYEE MG ON E.MGR = MG.EMPNO;

-- Q6 --
SELECT
E.ENAME AS EMPLOYEE_NAME, E.JOB AS EMPLOYEE_JOB,
E.SAL * 12 AS ANNUAL_SALARY,E.DEPTNO AS DEPARTMENT_NUMBER,
D.DNAME AS DEPARTMENT_NAME,
SG.GRADE
FROM
EMPLOYEE E
INNER JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
INNER JOIN SALGRADE SG ON E.SAL BETWEEN MINPAY AND MAXPAY
WHERE 
E.SAL * 12 = 3600
OR
E.JOB<> 'CLERK';


